apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: catalog-service
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: acme-fitness
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
    #    - name: annotations
    #      value:
    #        autoscaling.knative.dev/minScale: "1"
    - name: testing_pipeline_params
      value:
        testing-sub-path: "apps/acme-catalog"
  source:
    git:
      ref:
        branch: Azure
      url: https://github.com/jlafata/acme-fitness-store
    subPath: apps/acme-catalog