apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: payment-service
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: acme-fitness
    apps.tanzu.vmware.com/has-tests: "true"
spec:
#  params:
#    - name: annotations
#      value:
#        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/jlafata/acme-fitness-store
    subPath: apps/acme-payment